### ISSUE TITLE
2.7 - I have to configure network devices twice

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#1464] opened 2020-08-11 09:21 UTC
Bug originally filed by bladernr at https://bugs.launchpad.net/bugs/1878932

MAAS version is `2.7.1~beta1 (8260-g.c0c9e2acd-0ubuntu1~18.04.1)`

When I try to change the network configuration for an interface on a system I am forced to change it twice.

Steps:
1: Select Edit physical on desired interface
2: change Fabric, and configure IP address on the appropriate subnet
3: Save
4: Notice that the interface, instead of having the new config is now marked Unconfigured
5: Repeat steps 1 - 3 again
6: Save
7: NOW the interface is configured.  

I have attached a video showing this happening.

**Comment by sparkiegeek** [comment] 2020-11-24 18:50
https://bugs.launchpad.net/maas/+bug/1878932/+attachment/5372145/+files/maas.ogv <- the video

**Comment by huwshimi** [comment] 2021-04-26 01:56
Duplicate of https://github.com/canonical-web-and-design/maas-ui/issues/1521

**Closed by huwshimi** 2021-04-26 01:56 UTC
Labels: Affects 2.7 :bug:, Machines, Priority: High
