### ISSUE TITLE
No spinner when checking power

### ISSUE THREAD

**Issue by lilyvidenova** [canonical-web-and-design/maas-ui#813] opened 2020-02-18 14:10 UTC
The power icon should be changed to the spinner icon when checking power for a machine when using the in-table actions

**Comment by huwshimi** [comment] 2020-02-18 23:03
Related to: https://github.com/canonical-web-and-design/maas-ui/issues/781

**Comment by Caleb-Ellis** [comment] 2022-05-12 04:36
Still valid

**Comment by Caleb-Ellis** [comment] 2022-05-12 04:38
Actually a duplicate of #781

**Closed by Caleb-Ellis** 2022-05-12 04:38 UTC
Labels: Priority: Low, Bug 🐛
