### ISSUE TITLE
Strange behaviour in the Side Nav

### ISSUE THREAD

**Issue by amylily1011** [canonical-web-and-design/maas-ui#2027] opened 2021-01-04 15:47 UTC
I found a strange behaviour when I was browsing around the settings side Nav

To replicate:
[1]. click on General (under configuration)
- the tab is highlighted with a gray background

[2]. click configuration
- the "General" tab is highlight with a black border on the left

The same behaviour goes for all other Navs. The strangest one is when I click "Users" the tab is highlighted in gray. Then I click "Images" the "Users" tab is still highlighted in gray but with black border on the left.

reference to [1]
![Screen Shot 2021-01-04 at 3.40.19 PM.png](https://images.zenhubusercontent.com/5e6628e0ff9a3ccb84677b2f/0344b3f8-c4d2-4b47-9438-98712c0ccdb1)

reference to [2]
![Screen Shot 2021-01-04 at 3.40.30 PM.png](https://images.zenhubusercontent.com/5e6628e0ff9a3ccb84677b2f/cf4781e4-4a27-4018-89ec-446e6dca3fa4)

**Comment by Caleb-Ellis** [comment] 2021-02-10 09:03
Duplicate of https://github.com/canonical-web-and-design/maas-ui/issues/2024

**Closed by Caleb-Ellis** 2021-02-10 09:03 UTC
Labels: Bug 🐛, Priority: Low
