### ISSUE TITLE
TypeError: Cannot read property 'send' of null

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#1387] opened 2020-07-13 06:39 UTC
https://sentry.is.canonical.com/canonical/maas-ui/issues/10634/?referrer=github_plugin

```
TypeError: Cannot read property 'send' of null
  at RegionConnection.send (/MAAS/r/1.4d60becd58cd8d3cc327.js:33439:20)
  at RegionConnection.callMethod (/MAAS/r/1.4d60becd58cd8d3cc327.js:33490:54)
  at GeneralManager._loadData (/MAAS/r/1.4d60becd58cd8d3cc327.js:33804:178)
  at None (/MAAS/r/1.4d60becd58cd8d3cc327.js:33813:523)
  at Object.forEach (/MAAS/r/1.4d60becd58cd8d3cc327.js:4139:54)
...
(8 additional frame(s) were not displayed)
```

**Comment by huwshimi** [comment] 2020-07-13 06:49
Duplicate of https://github.com/canonical-web-and-design/maas-ui/issues/1254. Fix committed and backported.

**Closed by huwshimi** 2020-07-13 06:49 UTC

**Comment by anthonydillon** [comment] 2020-07-13 06:51
Thanks, marked as resolved in Sentry.
